hardware:
 U3LV:
  enabled: True
  sensors:
   EI1050:
    enabled: True
   LABINT:
    enabled: True
   LJDIGITALIN:
    enabled: True
   LJANALOGIN:
    enabled: True
   LJCURRENTIN:
    enabled: True
  controllers:
   KEPCO:
    enabled: True
   LJTDAC:
    enabled: True
 U3HV:
  enabled: True
  sensors:
   EI1050:
    enabled: True
   LABINT:
    enabled: True
   LJDIGITALIN:
    enabled: True
   LJANALOGIN:
    enabled: True
   LJCURRENTIN:
    enabled: True
  controllers:
   KEPCO:
    enabled: True
   LJTDAC:
    enabled: True
 NEW301:
  enabled: True
  controllers:
   NEWPORTAXIS:
    enabled: True
 CTC100:
  enabled: True
  sensors:
   CTCTHERMISTOR:
    enabled: True
 NIPCI6602:
  enabled: True
  sensors:
   DAQCOUNTER:
    enabled: True

 TEST: 
  enabled: True
  sensors:
   GAUSSSENSOR:
    enabled: True

sensors: 
 EI1050:
  enabled: True
 LABINT:
  enabled: True
 GAUSSSENSOR:
  enabled: True
 CTCTHERMISTOR:
  enabled: True
 DAQCOUNTER: 
  enabled: True
 LJDIGITALIN:
  enabled: True
 LJANALOGIN:
  enabled: True
 LJCURRENTIN:
  enabled: True

controllers: 
 KEPCO:
  enabled: True
 LJTDAC: 
  enabled: True
 NEWPORTAXIS:
  enabled: True

