from abstract_controller import AbstractController
from controller_factory import ControllerFactory
from controller_manager import ControllerManager
from kepco import KepcoSupply
from labjack import LJTDAC
from newport import Newport301Axis

# Register all predefined Sensors here
ControllerManager.register_controller(KepcoSupply)
ControllerManager.register_controller(LJTDAC)
ControllerManager.register_controller(Newport301Axis)